---
server:
  port: "${PORT:8080}"
  servlet:
    context-path: "/api/v1"
  forward-headers-strategy: "framework"
spring:
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:dev}"
---
spring:
  config:
    activate:
      on-profile: "ssl"
server:
  port: "${SSL_PORT:8443}"
  ssl:
    enabled: true
    certificate: "classpath:ssl/origin.crt"
    certificate-private-key: "classpath:ssl/origin.key"
