package com.lofi.lofiapps.enums;

public enum RoleName {
  ROLE_CUSTOMER,
  ROLE_ADMIN,
  ROLE_BRANCH_MANAGER,
  ROLE_BACK_OFFICE,
  ROLE_SUPER_ADMIN,
  ROLE_MARKETING,
  ROLE_TEST,
  ROLE_SIMPLE,
  ROLE_EMPTY
}
